In [5]:
# 문제1. 송파 여행사 여름 성수기 예약일정에 대한 외부파일이다. 
# reservation_day.csv, hotelcode.csv 외부파일을 읽어서 다음 수행조건을 실행하시오

import numpy as np
import pandas as pd

reservation_day = pd.read_csv('reservation_day.csv', encoding='utf-8')
hotel_code = pd.read_csv('hotelcode.csv', encoding='utf-8')
reservation_day

           입실일     코드   종류    1박요금  예약인원  숙박일수
0   2024-07-20  MS001   펜션  120000     2     2
1   2024-07-20  SK001  리조트  135000     2     3
2   2024-07-20  TB001   펜션   98000     3     3
3   2024-07-20  LT001   호텔  250000     3     2
4   2024-07-20  BS001  리조트  125000     3     2
5   2024-07-20  HA001   호텔  270000     4     3
6   2024-07-20  KA001   호텔   32000     4     4
7   2024-07-20  BL001  리조트   75000     6     2
8   2024-07-21  LT001   호텔  250000     3     1
9   2024-07-21  BS001  리조트  125000     4     1
10  2024-07-21  HA001   호텔  270000     4     2
11  2024-07-21  KA001   호텔   32000     2     2
12  2024-08-03  MS001   펜션  120000     4     3
13  2024-08-03  SK001  리조트  135000     4     3
14  2024-08-03  TB001   펜션   98000     4     3
15  2024-08-03  LT001   호텔  250000     2     3
16  2024-08-03  BS001  리조트  125000     4     2
17  2024-08-03  HA001   호텔  270000     4     3
18  2024-08-03  KA001   호텔   32000     6     4
19  2024-08-03  BL001  리조트   75000     6     2
20  2024-08-04  LT001   호텔  250000     2     1
21  2024-08-04  HA001   호텔  270000     2     2
22  2024-08-04  TB001   펜션   98000     6     2
23  2024-08-04  KA001   호텔   32000     4     2
24  2024-08-04  BL001  리조트   75001     2     3

In [4]:
hotel_code

      코드   지역      숙소명
0  MS001  서부권    엠스테이
1  SK001  동부권   스카이베이
2  TB001  동부권     더비치
3  LT001  동부권    롯데캐슬
4  BS001  서부권    베스트뷰
5  HA001  서귀포   하야트호텔
6  KA001  서귀포   KAL호텔
7  BL001  남해권    푸른바다

In [7]:
# 1. 코드가 일치한 키 값을 기준으로 두개의 파일을 병합
reservation = pd.merge(reservation_day, hotel_code, on='코드', how='inner')
reservation

           입실일     코드   종류    1박요금  예약인원  숙박일수   지역      숙소명
0   2024-07-20  MS001   펜션  120000     2     2  서부권    엠스테이
1   2024-07-20  SK001  리조트  135000     2     3  동부권   스카이베이
2   2024-07-20  TB001   펜션   98000     3     3  동부권     더비치
3   2024-07-20  LT001   호텔  250000     3     2  동부권    롯데캐슬
4   2024-07-20  BS001  리조트  125000     3     2  서부권    베스트뷰
5   2024-07-20  HA001   호텔  270000     4     3  서귀포   하야트호텔
6   2024-07-20  KA001   호텔   32000     4     4  서귀포   KAL호텔
7   2024-07-20  BL001  리조트   75000     6     2  남해권    푸른바다
8   2024-07-21  LT001   호텔  250000     3     1  동부권    롯데캐슬
9   2024-07-21  BS001  리조트  125000     4     1  서부권    베스트뷰
10  2024-07-21  HA001   호텔  270000     4     2  서귀포   하야트호텔
11  2024-07-21  KA001   호텔   32000     2     2  서귀포   KAL호텔
12  2024-08-03  MS001   펜션  120000     4     3  서부권    엠스테이
13  2024-08-03  SK001  리조트  135000     4     3  동부권   스카이베이
14  2024-08-03  TB001   펜션   98000     4     3  동부권     더비치
15  2024-08-03  LT001   호텔  250000     2     3  동부권    롯데캐슬
16  2024-08-03  BS001  리조트  125000     4     2  서부권    베스트뷰
17  2024-08-03  HA001   호텔  270000     4     3  서귀포   하야트호텔
18  2024-08-03  KA001   호텔   32000     6     4  서귀포   KAL호텔
19  2024-08-03  BL001  리조트   75000     6     2  남해권    푸른바다
20  2024-08-04  LT001   호텔  250000     2     1  동부권    롯데캐슬
21  2024-08-04  HA001   호텔  270000     2     2  서귀포   하야트호텔
22  2024-08-04  TB001   펜션   98000     6     2  동부권     더비치
23  2024-08-04  KA001   호텔   32000     4     2  서귀포   KAL호텔
24  2024-08-04  BL001  리조트   75001     2     3  남해권    푸른바다

In [8]:
# 2. 숙박요금 = 1박요금 * 숙박일수
reservation['숙박요금'] = reservation['1박요금'] * reservation['숙박일수']
reservation

           입실일     코드   종류    1박요금  예약인원  숙박일수   지역      숙소명    숙박요금
0   2024-07-20  MS001   펜션  120000     2     2  서부권    엠스테이   240000
1   2024-07-20  SK001  리조트  135000     2     3  동부권   스카이베이   405000
2   2024-07-20  TB001   펜션   98000     3     3  동부권     더비치   294000
3   2024-07-20  LT001   호텔  250000     3     2  동부권    롯데캐슬   500000
4   2024-07-20  BS001  리조트  125000     3     2  서부권    베스트뷰   250000
5   2024-07-20  HA001   호텔  270000     4     3  서귀포   하야트호텔   810000
6   2024-07-20  KA001   호텔   32000     4     4  서귀포   KAL호텔   128000
7   2024-07-20  BL001  리조트   75000     6     2  남해권    푸른바다   150000
8   2024-07-21  LT001   호텔  250000     3     1  동부권    롯데캐슬   250000
9   2024-07-21  BS001  리조트  125000     4     1  서부권    베스트뷰   125000
10  2024-07-21  HA001   호텔  270000     4     2  서귀포   하야트호텔   540000
11  2024-07-21  KA001   호텔   32000     2     2  서귀포   KAL호텔    64000
12  2024-08-03  MS001   펜션  120000     4     3  서부권    엠스테이   360000
13  2024-08-03  SK001  리조트  135000     4     3  동부권   스카이베이   405000
14  2024-08-03  TB001   펜션   98000     4     3  동부권     더비치   294000
15  2024-08-03  LT001   호텔  250000     2     3  동부권    롯데캐슬   750000
16  2024-08-03  BS001  리조트  125000     4     2  서부권    베스트뷰   250000
17  2024-08-03  HA001   호텔  270000     4     3  서귀포   하야트호텔   810000
18  2024-08-03  KA001   호텔   32000     6     4  서귀포   KAL호텔   128000
19  2024-08-03  BL001  리조트   75000     6     2  남해권    푸른바다   150000
20  2024-08-04  LT001   호텔  250000     2     1  동부권    롯데캐슬   250000
21  2024-08-04  HA001   호텔  270000     2     2  서귀포   하야트호텔   540000
22  2024-08-04  TB001   펜션   98000     6     2  동부권     더비치   196000
23  2024-08-04  KA001   호텔   32000     4     2  서귀포   KAL호텔    64000
24  2024-08-04  BL001  리조트   75001     2     3  남해권    푸른바다   225003

In [38]:
# 3. 열 ["코드","숙소명"]을 기준으로 데이터프레임 그룹을 진행
reservation.groupby(['코드','숙소명']).sum()

,,입실일,종류,1박요금,예약인원,숙박일수,지역,숙박요금
코드,숙소명,,,,,,,
BL001,푸른바다,2024-07-202024-08-032024-08-04,리조트리조트리조트,225001,14,7,남해권남해권남해권,525003
BS001,베스트뷰,2024-07-202024-07-212024-08-03,리조트리조트리조트,375000,11,5,서부권서부권서부권,625000
HA001,하야트호텔,2024-07-202024-07-212024-08-032024-08-04,호텔호텔호텔호텔,1080000,14,10,서귀포서귀포서귀포서귀포,2700000
KA001,KAL호텔,2024-07-202024-07-212024-08-032024-08-04,호텔호텔호텔호텔,128000,16,12,서귀포서귀포서귀포서귀포,384000
LT001,롯데캐슬,2024-07-202024-07-212024-08-032024-08-04,호텔호텔호텔호텔,1000000,10,7,동부권동부권동부권동부권,1750000
MS001,엠스테이,2024-07-202024-08-03,펜션펜션,240000,6,5,서부권서부권,600000
SK001,스카이베이,2024-07-202024-08-03,리조트리조트,270000,6,6,동부권동부권,810000
TB001,더비치,2024-07-202024-08-032024-08-04,펜션펜션펜션,294000,13,8,동부권동부권동부권,784000

In [54]:
# 4. 예약건수를 구하여 추가
reservation2 = reservation.groupby(['코드', '숙소명']).agg({'예약인원': 'sum', '숙박일수': 'sum', '숙박요금': 'sum', '입실일': 'count'})
reservation2.rename(columns={'입실일': '예약건수'})

              예약인원  숙박일수     숙박요금  예약건수
코드    숙소명
BL001 푸른바다      14     7   525003     3
BS001 베스트뷰      11     5   625000     3
HA001 하야트호텔     14    10  2700000     4
KA001 KAL호텔     16    12   384000     4
LT001 롯데캐슬      10     7  1750000     4
MS001 엠스테이       6     5   600000     2
SK001 스카이베이      6     6   810000     2
TB001 더비치       13     8   784000     3

In [55]:
# 5. 숙박요금 기준으로 내림차순 정렬
reservation2.sort_values(by='숙박요금', ascending=False)

              예약인원  숙박일수     숙박요금  입실일
코드    숙소명
HA001 하야트호텔     14    10  2700000    4
LT001 롯데캐슬      10     7  1750000    4
SK001 스카이베이      6     6   810000    2
TB001 더비치       13     8   784000    3
BS001 베스트뷰      11     5   625000    3
MS001 엠스테이       6     5   600000    2
BL001 푸른바다      14     7   525003    3
KA001 KAL호텔     16    12   384000    4

In [ ]:
# 외부 데이터 보내기
reservation.to_excel("송파성수기예약일정.xlsx", index=False, sheet_name="호텔예약", encoding='utf-8')